name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  Deloy :
    runs-on: ubuntu-latest
    steps:
      - name: Connect to EC2 with SSH
        uses: appleboy/ssh-actions@v1.0.3
        with:
          host: ${{secrets.EC2_HOST}}
          username: ${{secrets.EC2_USERNAME}}
          key: ${{secrets.EC2_PRIVATE_KEY}}
          script_stop: true
          script: |
            cd /home/ubuntu/backend
            git pull origin main
            ./gradlew clean build
            sudo fuser -k -n tcp 8088 || true
            nohup java -jar build/libs/*SANPSHOT.jar > ./output.log 2>&1 & 
            
