name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  Deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Connect to EC2 with SSH
        uses: appleboy/ssh-action@v1.0.3
        env:
          APPLICATION_PROPERTIES: ${{secrets.APPLICATION_PROPERTIES}}
        with:
          host: ${{secrets.EC2_HOST}}
          username: ${{secrets.EC2_USERNAME}}
          key: ${{secrets.EC2_PRIVATE_KEY}}
          envs: APPLICATION_PROPERTIES
          script_stop: true
          script: |
            cd /home/ubuntu/backend
            rm -rf src/main/resources/application-dev.yml
            git pull origin main
            echo "$APPLICATION_PROPERTIES" > src/main/resources/application-dev.yml
            ./gradlew clean build
            sudo fuser -k -n tcp 8088 || true
            nohup java -jar build/libs/*SNAPSHOT.jar > ./output.log 2>&1 & 
            
